{
 "title": "Book API Dashboard",
 "refresh": "15s",
 "panels": [
  {
   "title": "Request Rate (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(flask_http_request_total[1m])",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "Request Latency p95 (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(flask_http_request_duration_seconds_bucket[2m]))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "5xx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(flask_http_request_total{status=~\"5..\"}[2m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "PostgreSQL Active Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=\"bookdb\"}",
     "legendFormat": "Active connections"
    }
   ]
  }
 ]
}